import os

# ── 0002_opportunity: current schema matching models.py ──
f0002_opp = (
    "# Generated by Django 5.2.12 on 2026-03-30 16:00\n\n"
    "import django.db.models.deletion\n"
    "from django.conf import settings\n"
    "from django.db import migrations, models\n\n\n"
    "class Migration(migrations.Migration):\n\n"
    "    dependencies = [\n"
    "        ('pages', '0001_initial'),\n"
    "        migrations.swappable_dependency(settings.AUTH_USER_MODEL),\n"
    "    ]\n\n"
    "    operations = [\n"
    "        migrations.CreateModel(\n"
    "            name='Opportunity',\n"
    "            fields=[\n"
    "                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),\n"
    "                ('title', models.CharField(max_length=200)),\n"
    "                ('description', models.TextField()),\n"
    "                ('category', models.CharField(max_length=50)),\n"
    "                ('required_skills', models.TextField(blank=True, default='')),\n"
    "                ('opportunity_type', models.CharField(choices=[('volunteer', 'Volunteer'), ('internship', 'Internship'), ('job', 'Job')], default='volunteer', max_length=20)),\n"
    "                ('location', models.CharField(max_length=200)),\n"
    "                ('duration', models.CharField(choices=[('one-time', 'One-time'), ('recurring', 'Recurring')], default='one-time', max_length=20)),\n"
    "                ('hours_per_week', models.IntegerField(blank=True, null=True)),\n"
    "                ('application_deadline', models.DateField(blank=True, null=True)),\n"
    "                ('posted_date', models.DateTimeField(auto_now_add=True)),\n"
    "                ('is_active', models.BooleanField(default=True)),\n"
    "                ('organization', models.ForeignKey(limit_choices_to={'user_type': 'organization'}, on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to=settings.AUTH_USER_MODEL)),\n"
    "            ],\n"
    "            options={'ordering': ['-posted_date']},\n"
    "        ),\n"
    "    ]\n"
)

# ── 0003_opportunity_application_deadline_and_more: empty (fields already in 0002) ──
f0003_opp = (
    "# Generated by Django 5.2.12 on 2026-03-30 16:18\n\n"
    "from django.db import migrations\n\n\n"
    "class Migration(migrations.Migration):\n\n"
    "    dependencies = [\n"
    "        ('pages', '0002_opportunity_studentopportunity'),\n"
    "        ('pages', '0003_sync_legacy_application_schema'),\n"
    "    ]\n\n"
    "    operations = [\n"
    "    ]\n"
)

# ── 0002_conversation_message_faqsuggestion: Conversation in DB, Message/FAQ state only ──
f0002_conv = (
    "# Generated by Django 5.2.12 on 2026-03-30 16:06\n\n"
    "import django.db.models.deletion\n"
    "from django.conf import settings\n"
    "from django.db import migrations, models\n\n\n"
    "class Migration(migrations.Migration):\n\n"
    "    dependencies = [\n"
    "        ('pages', '0001_initial'),\n"
    "        migrations.swappable_dependency(settings.AUTH_USER_MODEL),\n"
    "    ]\n\n"
    "    operations = [\n"
    "        migrations.CreateModel(\n"
    "            name='Conversation',\n"
    "            fields=[\n"
    "                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),\n"
    "                ('created_at', models.DateTimeField(auto_now_add=True)),\n"
    "                ('last_message_at', models.DateTimeField(auto_now=True)),\n"
    "                ('organization', models.ForeignKey(limit_choices_to={'user_type': 'organization'}, on_delete=django.db.models.deletion.CASCADE, related_name='organization_conversations', to=settings.AUTH_USER_MODEL)),\n"
    "                ('volunteer', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_conversations', to=settings.AUTH_USER_MODEL)),\n"
    "            ],\n"
    "            options={'ordering': ['-last_message_at'], 'unique_together': {('volunteer', 'organization')}},\n"
    "        ),\n"
    "        migrations.SeparateDatabaseAndState(\n"
    "            state_operations=[\n"
    "                migrations.CreateModel(\n"
    "                    name='Message',\n"
    "                    fields=[\n"
    "                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),\n"
    "                        ('content', models.TextField()),\n"
    "                        ('timestamp', models.DateTimeField(auto_now_add=True)),\n"
    "                        ('is_read', models.BooleanField(default=False)),\n"
    "                        ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='pages.conversation')),\n"
    "                        ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),\n"
    "                    ],\n"
    "                    options={'ordering': ['timestamp']},\n"
    "                ),\n"
    "                migrations.CreateModel(\n"
    "                    name='FAQSuggestion',\n"
    "                    fields=[\n"
    "                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),\n"
    "                        ('faq_content', models.TextField()),\n"
    "                        ('relevance_score', models.FloatField(default=0.0)),\n"
    "                        ('was_accepted', models.BooleanField(default=False)),\n"
    "                        ('created_at', models.DateTimeField(auto_now_add=True)),\n"
    "                        ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_suggestions', to='pages.message')),\n"
    "                    ],\n"
    "                    options={'ordering': ['-relevance_score']},\n"
    "                ),\n"
    "            ],\n"
    "            database_operations=[],\n"
    "        ),\n"
    "    ]\n"
)

# ── 0005_message: normal CreateModel (state doesn't have old Message on this branch) ──
f0005 = (
    "# Generated by Django 5.2.12 on 2026-04-15 03:53\n\n"
    "import django.db.models.deletion\n"
    "from django.conf import settings\n"
    "from django.db import migrations, models\n\n\n"
    "class Migration(migrations.Migration):\n\n"
    "    dependencies = [\n"
    "        ('pages', '0004_merge_20260411_2219'),\n"
    "        migrations.swappable_dependency(settings.AUTH_USER_MODEL),\n"
    "    ]\n\n"
    "    operations = [\n"
    "        migrations.CreateModel(\n"
    "            name='Message',\n"
    "            fields=[\n"
    "                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),\n"
    "                ('subject', models.CharField(max_length=200)),\n"
    "                ('content', models.TextField()),\n"
    "                ('sent_at', models.DateTimeField(auto_now_add=True)),\n"
    "                ('is_read', models.BooleanField(default=False)),\n"
    "                ('recipient', models.ForeignKey(limit_choices_to={'user_type': 'organization'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),\n"
    "                ('sender', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),\n"
    "            ],\n"
    "            options={'ordering': ['-sent_at']},\n"
    "        ),\n"
    "    ]\n"
)

# ── 0003_sync_legacy_application_schema: depends on both 0002_opportunity and 0002_organizationfollow ──
f0003_sync = open('pages/migrations/0003_sync_legacy_application_schema.py', encoding='utf-8').read()
if "('pages', '0002_opportunity')," not in f0003_sync:
    f0003_sync = f0003_sync.replace(
        "        ('pages', '0002_organizationfollow'),",
        "        ('pages', '0002_organizationfollow'),\n        ('pages', '0002_opportunity'),"
    )

# ── 0009_reconcile_schema: SQLite-compatible version ──
f0009 = open('pages/migrations/0009_reconcile_schema.py', encoding='utf-8').read()
f0009_new = '''import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def reconcile_schema(apps, schema_editor):
    """Reconcile schema - SQLite-compatible version."""
    connection = schema_editor.connection
    introspection = connection.introspection

    with connection.cursor() as cursor:
        existing_tables = set(introspection.table_names())

        # Create StudentOpportunity if missing
        so_table = 'pages_studentopportunity'
        if so_table not in existing_tables:
            StudentOpportunity = apps.get_model('pages', 'StudentOpportunity')
            schema_editor.create_model(StudentOpportunity)
        else:
            so_cols = {col.name for col in introspection.get_table_description(cursor, so_table)}
            if 'date_pending' not in so_cols:
                cursor.execute("ALTER TABLE pages_studentopportunity ADD COLUMN date_pending datetime NULL")

        # Create Notification if missing
        notif_table = 'pages_notification'
        if notif_table not in existing_tables:
            Notification = apps.get_model('pages', 'Notification')
            schema_editor.create_model(Notification)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_merge_20260427_2024'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(reconcile_schema, noop_reverse),
    ]
'''

with open('pages/migrations/0002_opportunity.py', 'w', encoding='utf-8') as f:
    f.write(f0002_opp)
print('0002_opportunity written')

with open('pages/migrations/0003_opportunity_application_deadline_and_more.py', 'w', encoding='utf-8') as f:
    f.write(f0003_opp)
print('0003_opportunity_application_deadline_and_more written')

with open('pages/migrations/0002_conversation_message_faqsuggestion.py', 'w', encoding='utf-8') as f:
    f.write(f0002_conv)
print('0002_conversation_message_faqsuggestion written')

with open('pages/migrations/0005_message.py', 'w', encoding='utf-8') as f:
    f.write(f0005)
print('0005_message written')

with open('pages/migrations/0003_sync_legacy_application_schema.py', 'w', encoding='utf-8') as f:
    f.write(f0003_sync)
print('0003_sync_legacy_application_schema written')

with open('pages/migrations/0009_reconcile_schema.py', 'w', encoding='utf-8') as f:
    f.write(f0009_new)
print('0009_reconcile_schema written')

# Fix views.py: replace NOW() with CURRENT_TIMESTAMP
views = open('pages/views.py', encoding='utf-8').read()
count = views.count('NOW()')
views = views.replace('NOW()', 'CURRENT_TIMESTAMP')
open('pages/views.py', 'w', encoding='utf-8').write(views)
print(f'views.py: replaced {count} NOW() occurrence(s)')

# Fix 0004: create Notification with current schema matching models.py
f0004 = (
    "# Generated migration for Notification model and denial_reason field\n\n"
    "import django.db.models.deletion\n"
    "from django.conf import settings\n"
    "from django.db import migrations, models\n\n\n"
    "class Migration(migrations.Migration):\n\n"
    "    dependencies = [\n"
    "        ('pages', '0003_add_pending_status'),\n"
    "    ]\n\n"
    "    operations = [\n"
    "        migrations.AddField(\n"
    "            model_name='studentopportunity',\n"
    "            name='denial_reason',\n"
    "            field=models.TextField(blank=True, null=True),\n"
    "        ),\n"
    "        migrations.CreateModel(\n"
    "            name='Notification',\n"
    "            fields=[\n"
    "                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),\n"
    "                ('message', models.TextField()),\n"
    "                ('is_read', models.BooleanField(default=False)),\n"
    "                ('created_at', models.DateTimeField(auto_now_add=True)),\n"
    "                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),\n"
    "            ],\n"
    "            options={'ordering': ['-created_at']},\n"
    "        ),\n"
    "    ]\n"
)

with open('pages/migrations/0004_notification_and_denial_reason.py', 'w', encoding='utf-8') as f:
    f.write(f0004)
print('0004_notification_and_denial_reason written')