# Generated by Django 5.2.12 on 2026-03-23 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('opportunity_type', models.CharField(choices=[('volunteer', 'Volunteer'), ('internship', 'Internship'), ('job', 'Job')], default='volunteer', max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('duration', models.CharField(choices=[('one-time', 'One-time'), ('recurring', 'Recurring')], default='one-time', max_length=20)),
                ('hours_per_week', models.IntegerField(blank=True, null=True)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(limit_choices_to={'user_type': 'organization'}, on_delete=django.db.models.deletion.CASCADE, related_name='posted_opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-posted_date'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('responded_date', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True, help_text="Student's application message")),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='pages.opportunity')),
            ],
            options={
                'ordering': ['-applied_date'],
                'unique_together': {('student', 'opportunity')},
            },
        ),
    ]
