# Generated by Django 5.2.12 on 2026-03-30 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('cause', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=100)),
                ('skills_required', models.TextField(blank=True)),
                ('opportunity_type', models.CharField(choices=[('volunteer', 'Volunteer'), ('internship', 'Internship')], default='volunteer', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(limit_choices_to={'user_type': 'organization'}, on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
