# Generated by Django 5.2.12 on 2026-03-30 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_opportunity_studentopportunity'),
        ('pages', '0003_sync_legacy_application_schema'),
    ]

    operations = [
    ]
