# Generated by Django 5.2.14 on 2026-05-11 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_opportunity'),
        ('pages', '0002_organizationfollow'),
    ]

    operations = []
