# Generated by Django 5.2.12 on 2026-03-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_opportunity_studentopportunity'),
        ('pages', '0003_sync_legacy_application_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='application_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='required_skills',
            field=models.TextField(blank=True, default=''),
        ),
    ]
