# Generated by Django 5.2.12 on 2026-04-12 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_volunteerprofile_volunteerexperience'),
        ('pages', '0003_sync_legacy_application_schema'),
    ]

    operations = [
    ]
