# Generated by Django 5.2.12 on 2026-04-15 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_message_read_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(blank=True, help_text='If this is a reply, reference the original message.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='pages.message'),
        ),
    ]
