# Generated by Django 5.2.12 on 2026-04-27 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_opportunity_application_deadline_and_more'),
        ('pages', '0004_notification_and_denial_reason'),
        ('pages', '0007_message_reply_to'),
    ]

    operations = [
    ]
