# Generated by Django 5.2.12 on 2026-05-12 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_conversation_message_faqsuggestion'),
        ('pages', '0003_merge_0002_opportunity_0002_organizationfollow'),
        ('pages', '0005_merge_20260412_0001'),
        ('pages', '0009_reconcile_schema'),
    ]

    operations = [
    ]
