# Generated by Django 5.2.12 on 2026-05-11 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_conversation_message_faqsuggestion'),
        ('pages', '0009_reconcile_schema'),
    ]

    operations = [
    ]
