# Generated by Django 5.2.12 on 2026-05-12 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_merge_20260512_0134'),
        ('pages', '0012_volunteerprofile_location_interests'),
    ]

    operations = [
    ]
